### ISSUE TITLE
Net Framework

### ISSUE THREAD

**Issue by sec13b** [g3tsyst3m/elevationstation#2]
can you compile with old net framework 4.6.
thank you

**Comment by g3tsyst3m** [comment]
ElevationStation is written and compiled in standard C++ so there should not be a need for .NET.  Is there a particular error message you are receiving?

**Comment by g3tsyst3m** [comment]
closing this for now until further evidence is provided that would explain the issue in more detail

**Comment by sec13b** [comment]
on windows server 2016  last update of  framework  is 4.6. not run
